name: Build and Tag Docker

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Image
        id: build
        run: docker build -t dream-ml-predictor:latest .

      - name: Check Build Status
        id: build_status
        run: |
          echo "Build finished with status: $?"
          if [ $? -ne 0 ]; then
            echo "Build failed. Exiting."
            exit 1
          fi

      - name: Create and Push Tag
        if: steps.build_status.outcome == 'success'
        run: |
          git fetch --tags
          LATEST_TAG=$(git tag | sort -V | tail -n 1)
          NEW_TAG=$(echo $LATEST_TAG | awk -F. -v OFS=. '{$NF++;print}')
          git tag $NEW_TAG
          git push origin $NEW_TAG


      # - name: Set up aws
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: *region*

      # - name: Authenticate docker to ecr
      #   run: aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin *account*.dkr.ecr.*region*.amazonaws.com

      # - name: Tag Image
      #   run: docker tag dream-ml-predictor:latest *account*.dkr.ecr.*region*.amazonaws.com/my-repo:$NEW_TAG

      # - name: Push Image to ecr
      #   run: docker push *account*.dkr.ecr.*region*.amazonaws.com/my-repo:$NEW_TAG
